### ISSUE TITLE
2.10: new config files

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik-package#17]
Hello!

In 2.10 we have a new sub-folder in `config/` containing 2 new config files. I guess these files should be handled like the other config files (e.g. `config/global.php`…).

This folder might see new files added in the future, so if it's possible to handle the whole folder that would be great. This folder will **not** contain any user config file.

Folder: `config/environment/` (https://github.com/piwik/piwik/tree/master/config/environment)

Contains:

- `cli.php`
- `test.php`

**Comment by mattab** [comment]
Hi @aureq FYI something maybe important for the upcoming 2.10.0 release?
