### ISSUE TITLE
Let the auto-archive cron job write its log file to /var/log/piwik/archive.log

### ISSUE THREAD

**Issue by nicwortel** [piwik/piwik-package#19]
Currently the `piwik-archive` cron does not save any logging information at all (by default). But since a log directory is created by the package anyway (/var/log/piwik), wouldn't it be nice to let the cron job save its result to a log file in that directory? For instance /var/log/piwik/archive.log.

The only caveat would be that the job needs to be run by root instead of www-data. Would that be considered a bad practice?

**Comment by aureq** [comment]
Hi @nicwortel,

This has been fixed. I've also included a logrotate file so system administrator may keep and rotate the logs to their liking. The dependency on logrotate is "Recommended" but not compulsory though.

**Comment by aureq** [comment]
This is now available in 2.10.0 for debian/ubuntu. Thanks

**Comment by nicwortel** [comment]
Hi @aureq,

Thanks for the update! However, have you tested this? In my case (Ubuntu server), the logs can not be saved because the user www-data has no write access to the /var/log/piwik directory (owned by root).

Should the ownership of the /var/log/piwik directory be changed to www-data, or should the crontab be executed as root?

I previously ran the crontab as root but since the default cron file that comes with piwik contains 'www-data' as user, I wonder what the preferred solution is.

**Comment by aureq** [comment]
@nicwortel You're correct, the folder ownership should be www-data for sure. Feel free to update the permission, I will amend the package tomorrow and will also check the logrotate rule as well.

**Comment by aureq** [comment]
Hi @nicwortel I just pushed a new release (2.10.0-2) which addresses permission issue as you reported. Do you mind to have a look please ?

**Comment by aureq** [comment]
I just deployed 2.10.0-2 in production and it's fine permission wise.
