### ISSUE TITLE
Remove ".git" folder when creating zip archive.

### ISSUE THREAD

**Issue by aureq** [piwik/piwik-package#20]
Found in 2.10.0, usr/share/piwik/vendor/doctrine/cache/.git/

**Comment by mattab** [comment]
Hi @aureq  - thanks for report.  fixed in https://github.com/piwik/piwik-package/commit/97ff1702c68f6025c5a8ea45114822a41fe9bd2a

**Comment by aureq** [comment]
Thanks @mattab. I wrote the exact same change too, but you pushed first.
