### ISSUE TITLE
exclude bower.json, .bower.json and .bowerrc from archive (zip/tar.gz)

### ISSUE THREAD

**Issue by aureq** [piwik/piwik-package#21]
hi @mattab @mnapoli 

I found a lot of bower.json, .bower.json files and one .bowerrc.
The .deb already exclude these as it seems to be related to bower package management and dependencies.
Let me know if I also should exclude these from the official archives as well.

Cheers

**Comment by aureq** [comment]
Also, unsure about
* .travis.yml
* composer.json
* .coveralls.yml

Let me know if safe to be removed from the release.

**Comment by mnapoli** [comment]
Hi, indeed we could, though maybe not composer.json because it might be used in the future.

Is there any reason to remove them? I wouldn't go though that trouble if they don't affect anything, especially since they may change in the future.

**Comment by aureq** [comment]
It's mostly for cleanliness purpose.

**Comment by mnapoli** [comment]
OK I'm in theory +1 for that, I'm just afraid of possible side effects later if things changes. E.g. I would not remove `composer.json` files. The rest should be OK I guess.

**Comment by aureq** [comment]
ok, will do, thanks.

**Comment by mattab** [comment]
+1 with @mnapoli point

**Comment by tomduckering** [comment]
Some of these files (i.e. `bower.json`) are still included in the `manifest.inc.php`. This seems to cause warnings in the File Integrity section of the System Check Administration page.
