### ISSUE TITLE
Package upgrades should run DB update in postinst script

### ISSUE THREAD

**Issue by jnachtigall** [piwik/piwik-package#23]
I use [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) for nightly (security) updates. Works well as long as package upgrades are "self-contained", that is necessary server restarts/reloads etc are handled by the package upgrade itself. 

For the piwik package this does not seem to be the case. One has to manually run the DB update script:
`php /usr/share/piwik/console core:update `

I think the postinst script should include the db update step.

**Comment by aureq** [comment]
hi @jnachtigall 

Thank you for the suggestion. Though, I slightly disagree on this, but allow me to explain.

Updating the database may not be a good idea if the sysadmin is not fully aware of all the risks.
* High CPU usage if the database is big and potential side effects on database cluster
* Possible corruption (happened to me) and no way to revert back

Though, I do see your point and the needs behind your ticket. I will try to implement a package setting that will allow you to do this automatically if the package setting is enabled. I'll keep you updated as to what I'll be implementing.

**Comment by jnachtigall** [comment]
> I will try to implement a package setting that will allow you to do this automatically if the package setting is enabled. I'll keep you updated as to what I'll be implementing.

:+1:  Good idea

**Comment by danielhjames** [comment]
One way to handle this is to use a debconf question such as:

Upgrade Piwik database automatically? yes/no

Sysadmins who prefer to upgrade their database manually will have their 'no' choice saved in the debconf database for future upgrades. See http://www.fifi.org/doc/debconf-doc/tutorial.html

**Comment by jnachtigall** [comment]
Any news on this? I again had a piwik downtime due to the recent package upgrade

**Comment by jnachtigall** [comment]
For the upcoming 2.13 (security fix) there will be a db upgrade again. Hope you can fix this issue until then...

**Comment by aureq** [comment]
@jnachtigall No, I haven't forgotten you, at all. I've already prepared 2.13.0, but I need to test it to ensure it's all good. When this is done, I'll then implement that feature (I need it to).
It will come as a debconf "pin" that will allow the automatic db upgrade to happen.

**Comment by aureq** [comment]
@jnachtigall I finished the implementation. Let me know how it goes for you please.
Please note that you need to enable the automatic upgrade the first time either through the command line or apt-get. (`piwik/automatic-upgrade` => `true`)

**Comment by jnachtigall** [comment]
@aureq Works great, thank you :+1:
