### ISSUE TITLE
Priority should be optional not imporant

### ISSUE THREAD

**Issue by finnhughes** [piwik/piwik-package#25]
The debian/control script should set priority to optional. This would be more in keeping with the debain guidelines
https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-priority

In my case I included piwik in a repository and it got pulled into a build it shouldn't have simply because priority is set to important.

Thanks

**Comment by aureq** [comment]
@finnhughes 

Agreed with you, `debian/control` should be set to `Priority: optional`.
I'll keep this bug open until the next release.
