### ISSUE TITLE
Release tarball contains .git links

### ISSUE THREAD

**Issue by znerol** [piwik/piwik-package#27]
Since 2.10.0 the release tarball contains `.git` files in some places. These do not contain the actual submodule repository but simply represent a relative link pointing outside the source tree:

    $ cat ./libs/PiwikTracker/.git
    gitdir: ../../.git/modules/libs/PiwikTracker

As a result `git add` wreaks havoc when trying to check in newer piwik releases into an existing source tree:

    $ git add .
    fatal: Not a git repository: libs/PiwikTracker/../../.git/modules/libs/PiwikTracker

This seems to have appeared in 2.10.0:

    $ for v in 2.8.0 2.9.0 2.10.0 2.11.0 2.12.0; do echo $v && curl http://builds.piwik.org/piwik-$v.tar.gz 2>/dev/null | tar tz | grep '\.git$'; done
    2.8.0
    2.9.0
    2.10.0
    piwik/libs/PiwikTracker/.git
    2.11.0
    piwik/libs/PiwikTracker/.git
    2.12.0
    piwik/libs/PiwikTracker/.git
    piwik/misc/log-analytics/.git

**Comment by mattab** [comment]
Thanks for the report! 

I will release 2.12.1-rc1 in 1 hour or so so please try again... it should be fixed, let me know

**Comment by mattab** [comment]
Fixed in 2.12.1-b1 version (no more `.git` files)

**Comment by znerol** [comment]
Thanks, that works for me. I also welcome the removal of `.gitignore` from the project directory.
