### ISSUE TITLE
automatically update / initialize the database with the standard debian credentials

### ISSUE THREAD

**Issue by kaystrobach** [piwik/piwik-package#31]
* use /etc/mysql/debian.cnf to retrieve correct mysql root credentials
* create piwik database with utf-8
* create piwik user
* configure piwik
* import database
* create webuser for piwik

done!

**Comment by aureq** [comment]
@kaystrobach this is not necessarily advisable and may not be feasible yet.

1 - Not advisable as some user have their database on a separate server/cluster. I guess a prompt could be used to deal with that.

2 - Initialization
For the technical part, it would require some work from the Piwik team to expose the database creation process/setup. Remember that everything that's available to through the setup page, has to be entered through the package manager.

**Comment by aureq** [comment]
@kaystrobach You are welcome to share any pull request you may have and the team will review your work and eventually integrate it. We always appreciate when our users actively participate. Thanks

**Comment by mattab** [comment]
Hi @kaystrobach thanks for the suggestion. agreed with @aureq, in general it's important that Piwik super user actually goes through the Piwik installation process, we design it to be as simple and short as possible yet giving some important information (eg. info about the JS tracking code, cronjob, privacy settings at the end).  out of scope for debian package. see #29
