### ISSUE TITLE
Debian/Ubuntu MySQL autosetup by "dbconfig-common"

### ISSUE THREAD

**Issue by Reiner030** [piwik/piwik-package#40]
When I select automatic db upgrade I got in first installation this error message several times:

```
  [Zend_Db_Adapter_Exception]                                                   
  SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
```

without requests for host,user, password setup ... 

Perhaps you can check from another Debian package howto include packe/functions of "dbconfig-common" (e.g. from package "icinga2-ido-mysql".  "phpmyadmin" )

It looks like that this is very easy to integrate into postinst script:

```
. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/phpmyadmin/config-db.php
```

and postrm script:

```
if [ "$1" = "purge" ]; then
    rm -f /etc/phpmyadmin/config-db.php
    if which ucf >/dev/null 2>&1; then
        ucf --debconf-ok --purge /etc/phpmyadmin/config-db.php
    fi
fi
```

**Comment by zeigerpuppy** [comment]
I am trying to install piwik via the debian package and I agree it needs a better way of configuring the database.
I am trying to use a datbase on another host, so I edited the global.ini.php with the database variables but the package fails to install with the error:
```
[PDOException]                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.log_visit' doesn't exist  
```

**Comment by aureq** [comment]
To be confirmed by @mattab but this may be a feature of Piwik Pro. At the moment, `config.ini.php` is generated by the web install wizard.

**Comment by mattab** [comment]
Confirmed @aureq: we have some automation code in Piwik PRO to pragmatically install Piwik using one console command. This code is not open source - so please consider becoming Piwik PRO client to benefit from it (and contribute to Piwik as a result!). 

-> when using our debian package tool, a user installing Piwik has to  go through the 5min web UI install. 

> so I edited the global.ini.php with the database variables but the package fails to install with the error:

FYI: don't edit global.ini.php but edit your config.ini.php file only.
