### ISSUE TITLE
Failing to install on debian jessie

### ISSUE THREAD

**Issue by spacekookie** [piwik/piwik-package#51]
Following the instructions from [debian.piwik.org](debian.piwik.org) on a fresh installation on Debian Jessie (running in a container) fails while configuring the piwik package with the following errors:

```console
The configuration file {/usr/share/piwik/config/config.ini.php} has not been found or could not be read.
 » Please check that /usr/share/piwik/config/config.ini.php is readable by the user 'root'. 


 [Zend_Db_Adapter_Exception]                                                                                  
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)  
                                                                                                               

[PDOException]                                                                                               
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)  
                                                                                                               
core:update [--yes]
dpkg: error processing package piwik (--configure):
 subprocess installed post-installation script returned error exit status 255
```

Btw, when I manually install the mysql-server the error is replaced with an "Access Denied to root@localhost" or something like that. But I would assume that the piwik package should take care of all of that.

`/usr/share/piwik/config/config.ini.php` doesn't seem to exist on my system. How can I fix this?

**Comment by aureq** [comment]
Hi @spacekookie 

In order to install piwik correctly, the `config.ini.php` must be present. `/usr/share/piwik/config` is a symbolic link to `/etc/piwik/` so check it's pointing correctly to that folder.

Furthermore, the configuration file `config.ini.php` must contain the correct database credentials:
```ini
; <?php exit; ?> DO NOT REMOVE THIS LINE
; file automatically generated or modified by Piwik; you can manually override the default values in global.ini.php by redefining them in this file.
[database]
host = "localhost"
username = "piwik"
password = "somesup3rSkretP4ssw0rd!~"
dbname = "piwik"
tables_prefix = "piwik_"
```

**Comment by spacekookie** [comment]
Hey there. The symlink from `/usr/share/piwik/config` was correct. I got an error because `config.ini.php` didn't exist.

Using your example I added a file, installed the `mysql-server` package but it then complained to not find a DB. So I went into the mysql console and created a "piwik" database and a "piwik" user to access it.

Now a new error message comes up: 
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.piwik_log_visit' doesn't exist
```

This can't seriously be how one goes about configuring this software. Isn't a package supposed to make it easier to install and configure a piece of software? The fact that the config is missing, it's not installing all dependencies (SQL server) and now having to do manual configuration feels like something has seriously gone wrong.

And I hope that it can be fixed because if I manually wanted to configure piwik I would install it from source.

**Comment by aureq** [comment]
Hi @spacekookie 

Have you followed the documentation on how to install piwik? http://piwik.org/docs/installation/
The database schema is created by the web gui and not from the Debian package itself.

To get a better understanding at why the Debian package doesn't provide automated installation, please have a look at #44

**Comment by CAPSLOCK2000** [comment]
But the package won't install without the database, so that's a catch-22.

**Comment by cristiaan3003** [comment]
Same error when I try install-> apt-get install piwik piwik (3.0.2-1)  (debian 8)

**Comment by openbrian** [comment]
I'm also having issues installing piwik.  I'm installing on Ubuntu 16.04 LTS (xennial).  config.ini.php was not created in /etc/piwik/  The MySQL database was not created.  The postinst script looks to install the apache configuration (symlink) in /etc/apache2/conf.d/, by on Ubuntu there is no /etc/apache2/conf.d/.   The postinst script therefor assumes Apache is not installed. There are  however a conf-available and conf-enabled folders.

I'm trying to put the pieces of this install together manually.

php /usr/share/piwki/console core:update --yes fails with this error message
[Zend_Db_Statement_Exception]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.log_visit' doesn't exist

[PDOException]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.log_visit' doesn't exist

debian.piwik.org files haven't been updated since March 7th.

**Comment by openbrian** [comment]
Going to http://myhost/piwik reports this confusing error:

Error: Piwik is already installed. 

Original error was "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'piwik.option' doesn't exist".

Go back to Piwik.

**Comment by openbrian** [comment]
I'm not 100% sure, but I think Piwik is expecting a passwordless root account in MySQL. After clearing the password, the website installation wizard appeared and I walked through about 6 steps to complete the install. I had also removed the config.ini.php file before doing that.

**Comment by aureq** [comment]
@spacekookie Thank you for your patience on this. I've been rather busy (and depressed) but I'm hoping the patch will address the issue.

**Comment by spacekookie** [comment]
@aureq Hey there. I'm looking forward to being able to install a piwik more easily again :P Also hope you feel better (been there, done that) *hugs*

Hoping to hear from you again soon.

**Comment by aureq** [comment]
@spacekookie Thank you for your kind words.

Piwik installs without a failure on a fresh debian and ubuntu server. However, it's the system admin to connect their piwik installation to a mysql/mariadb server whether it is local or remote.
