### ISSUE TITLE
Wording for database update unclear?

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-package#53]
I've just helped someone updating their debian package and there were a few minor usability things that weren't clear.

It once asked re whether to enable automatic database update and we thought we enable a setting to do this in the future automatically (the updates). Instead it would be maybe better to ask whether "someone wants to update the DB now". It would be also maybe good to mention that this is recommended unless it is a high traffic website. Also we weren't sure what would happen if we said "No" and didn't perform the update. Would we get the queries and be able to execute them manually? Maybe it would be good to mention the workflow if someone selects "no".

Also it asked whether to overwrite global.ini.php and the person was about to say "No keep my local file" but this can lead to problems with Piwik. Ideally the updater would always replace the global config I'd say

**Comment by aureq** [comment]
@tsteur 

- Messaging: I don't understand what you're trying to say (feel free to write in French if that's easier).
If the messaging isn't clear enough, then feel free to make a proposition. The text is stored in https://github.com/piwik/piwik-package/blob/master/debian/templates
If the upgrade is not performed, then I can add a custom messaging once the package has been installed. This is controlled at the end of https://github.com/piwik/piwik-package/blob/master/debian/postinst

- About the INI file, unless the file has changed between 2 updates, Debian should safely deploy the changes. This behavior is controlled by debian itself (apt), not via the package from what I know.

**Comment by tsteur** [comment]
> About the INI file, unless the file has changed between 2 updates, Debian should safely deploy the changes.

Awesome

> Messaging

The user that was using the package wasn't sure what is going to happen. eg
1) Will it perform a database update directly when selecting yes
2) And / or does this affect all database updates when there are any in the future
3) What happens when selecting no, how will the update be executed then.

I'm still not quite sure but I understand when selecting "yes", and there is a database update for Piwik (eg update from Piwik 2 to Piwik 3), it will perform a database update after updating the package and in the future, whenever there is a DB update, it will be executed automatically and one doesn't have to select it again?

Still not quite sure about the behaviour. Eg it wasn't clear whether there would be a DB update already executed with this update (many Piwik updates do not have a DB update) and which queries would be executed. It basically depends on the queries to decide whether it is worth updating the DB now or manually at a later time. I reckon I would first need to know the consequences of selecting "yes" and then I can better explain :)

**Comment by aureq** [comment]
Ok, so what you mean is the message displayed when prompting the user is not clear. And it's hard to understand whether 1 or 2 will happen. So, I can fix this messaging.
To answer the question, the db upgrade is performed after the package has been updated, and it remains as such for all future package upgrades when required. There's a debian (apt) command to change the behavior if needed.

**Comment by tsteur** [comment]
Sweet. In this case  the message is already pretty good. We would maybe need to change the message like below but it is probably way too long.

```
 Please choose whether you want to enable automatic database upgrade for your Piwik installation.
 .
 From time to time, Piwik database schema must be upgraded so Piwik
 can continue to work correctly. You have the ability to automate the
 process so the database is upgraded automatically. Though, you
 should ensure you have proper backup in place and keep in mind
that major Piwik version updates may come with many DB updates 
that can take a long time.

If you select yes, the database update will be executed and it remains as such for all future package upgrades when required. You can change this behavior with a debian (apt) command.

If you select no, you will need to take care of database updates yourself after a package upgrade. In such a case, Piwik will show the list of database queries that need to be executed in the UI.
```

**Comment by mattab** [comment]
:+1:

**Comment by aureq** [comment]
Closing this issue. Changed the `apt` command to proper `dpkg-reconfigure piwik` command.
